[package]
name = "nmbr9-z3"
version = "0.1.0"
authors = ["Matt Keeter <matt.j.keeter@gmail.com>"]
edition = "2018"

[dependencies]
itertools = "0.8"
z3 = { git = "https://github.com/prove-rs/z3.rs" }
rayon = "1.0"
rand = "0.6"
